name: Singleprogram CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install deps for building and testing
      run: sudo apt update; sudo apt install -y libxcb-xinerama0 libxcb-xinerama0-dev libxinerama1 libxinerama-dev ffmpeg stterm
    
    - name: Build
      run: make -j2
    
    - name: Run test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: sh .github/test.sh
