name: Singleprogram CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install deps for building and testing
      run: sudo apt update; sudo apt install -y libxcb-xinerama0 libxcb-xinerama0-dev libxinerama1 libxinerama-dev ffmpeg stterm
    
    - name: Build
      run: make -j2
    
    - name: Run test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: sh .github/test.sh
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
      # A file, directory or wildcard pattern that describes what to upload
        path: output.png 
      # The desired behavior if no files are found using the provided path.
